version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.11.1@sha256:dcb16cd1320e7819c403e5291696b2955799060de1ea391f06e87cebb1d97b79
    working_directory: ~/workspace
    steps:
      - checkout
      - restore_cache:
          keys:
          - packages-{{ checksum "yarn.lock" }}
          - packages-
      - run:
          name: Install packages
          command: yarn install
      - save_cache:
          key: packages-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Lint
          command: yarn run lint
